version: '3'

volumes:
    data:

services:

  discovery:
    build: discovery-server/
    hostname: discovery
    ports:
      - "8761:8761"
#
#  mail:
#    build: message-sender-service/
#    ports:
#      - "8082:8082"
#    links:
#      - discovery

  web:
    build: web/
    ports:
      - "8081:8081"
    links:
      - discovery
      - neo4j

  neo4j:
    image: neo4j
    ports:
      - "7474:7474"
      - "7687:7687"
    volumes:
      - data:/data


#  docker run \
#  --publish=7474:7474 --publish=7687:7687 \
#  --volume=data:/data \
#  neo4j
