version: '3'

volumes:
    data:
    datadir:

services:

  discovery:
    container_name: discovery-server
    build: discovery-server/
    hostname: discovery
    ports:
      - "8761:8761"

  mail:
    container_name: mail-server
    build: message-sender-service/
    ports:
      - "8082:8082"
    depends_on:
      - discovery
      - mongo

  web:
    container_name: web-server
    build: web/
    ports:
      - "8081:8081"
    depends_on:
      - discovery
      - neo4j

  neo4j:
    container_name: neo4j-server
    image: neo4j
    ports:
      - "7474:7474"
      - "7687:7687"
    volumes:
      - data:/data


  mongo:
    image: mongo
#    restart: always
    container_name: mongodb
#    environment:
#      MONGO_INITDB_ROOT_USERNAME: test
#      MONGO_INITDB_ROOT_PASSWORD: test
    ports:
      - "2717:27017"
    volumes:
      - datadir:/data/db

