version: '3'

volumes:
  data:

services:

  web:
    build: web/
    ports:
      - 8081:8081


  mail:
    build: message-sender-service/
    ports:
      - 8082:8082

  discovery:
    build: discovery-server/

  db:
    data:/data