spring:
  application:
    name: message-sender-service

  mail:
    host: smtp.gmail.com
    port: 587
    protocol: smtp
    username:
    password:

  data:
    mongodb:
      host: localhost
      port: 2717
      database: emailStore


server:
  port: 8082
