spring:
  data:
    neo4j:
      uri: http://neo4j:7474
      username: neo4j
      password: test
  application:
    name: main-server

server:
  port: 8081


eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery:8761/eureka