spring:
  data:
    mongodb:
      host: mongo
      port: 2717
      database: email
#      username: test
#      password: test

eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery:8761/eureka