spring:
  application:
    name: message-sender-service

  mail:
    host: smtp.gmail.com
    port: 587
    protocol: smtp
    username: your@gmail.com
    password: your


eureka:

  client:
    serviceUrl:
      defaultZone: http://discovery:8761/eureka

server:
  port: 8082